# Gene-set analyses of the comorbidity sub-graphs

The gene-set counterpart of `4_10`: instead of drawing the sub-graph around each interface protein, we turn it into a **gene set** and confront it with the bulk RNA-seq DE gene lists of `4_00`.

Two analyses, on two pairings.

**The analyses.** *GOAT* tests the sub-graph's gene set for enrichment against the whole effect-size ranking of a gene list (the R `goat` package, via `rpy2`). The *intersection* is its naive counterpart — how much of the gene set is simply among the genes the list marks significant. They want different namespaces: GOAT matches the gene lists' `gene` column, which is the HGNC dataset's `entrez_id`, so its gene sets are `ncbigene`; the intersection matches the `symbol` column, so its gene sets are `hgnc.symbol`.

**The pairings.** COVID → PD, whose downstream side is the PD activity-flow maps, and COVID → AD, whose downstream side is the **AD BEL knowledge graph** — the same two `4_10` draws, with the same collection names, walk and `max_levels`. The AD side used to be out of reach here: BEL nodes carried only `uniprot` annotations, and they were labelled `BELModelElement` but not `ModelElement`, which is what the annotation helpers in `commute_dm.queries` match — so they returned nothing for a BEL node, silently. `2_00` now writes `hgnc.symbol`, `ncbigene`, `hgnc` and `uniprot` on the KG's HGNC-encoded proteins and labels its nodes `ModelElement`, which is all it took.

Nothing here writes to the database, and nothing here loads a map: gene sets need no drawing material, so this is a matter of seconds rather than the couple of minutes `4_10` spends hydrating.

In [1]:
%store -r

Unable to restore variable 'PD_DM_AF_BUILD_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'CBM_KG_CYPHER_DATA_FILE', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'COVID_DM_AF_BUILD_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'INTERFACE_INTERSECTION_UPSTREAM_AND_DOWNSTREAM_ANALYSIS_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'INTERFACE_GOAT_UPSTREAM_ANALYSIS_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'AD_KG_DATA_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'COVID_KG_CYPHER_DATA_FILE', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'AD_KG_CYPHER_DATA_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'AD_KG_CYPHER_DATA_FILE', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'INTERFACE_GOAT_DOWNSTREAM_ANALYSIS_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'PD_KG_CYPHER_DATA_FILE', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'INTERFACE_INTERSECTION_UPSTREAM_ANALYSIS_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'INTERFACE_INTERSECTION_DOWNSTREAM_ANALYSIS_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'INTERFACE_GOAT_UPSTREAM_AND_DOWNSTREAM_ANALYSIS_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
Unable to restore variable 'INTERFACE_ANALYSIS_GRAPHS_DIR', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>

In [2]:
import commute_dm.core
import commute_dm.submaps
import commute_dm.utils
import credentials
import momapy_kb.lpg.backends.neo4j
import momapy_kb.lpg.session

In [3]:
backend = momapy_kb.lpg.backends.neo4j.Neo4jBackend(
    hostname=credentials.NEO4J_URI,
    username=credentials.NEO4J_USERNAME,
    password=credentials.NEO4J_PASSWORD,
    notifications_min_severity="off",
)
session = momapy_kb.lpg.session.Session(backend)

## Parameters

One entry per pairing, holding exactly what `4_10` holds in its own parameter cell — the collection names, the interface to join over and the levels to walk — plus the output directory of each analysis and mode.

`max_levels` differs between the two for the reason `4_10` gives: the AD influence graph is far denser than an activity-flow map, so a level means much more there. `WITH_SUBUNITS` now means the same thing on both sides — a CellDesigner complex's subunits, and a BEL complex's or composite's members. A BEL **activity** is not a subunit and is always followed: `act(p(X))` is X in another form, the way an active CellDesigner species is still that species.

In [4]:
MIN_N_NODES = 5
WITH_SUBUNITS = True
P_VALUE_CUTOFF = 0.05
MODES = ["upstream", "downstream", "upstream_and_downstream"]

PAIRINGS = [
    {
        "name": "COVID -> PD",
        # The interface is the three-way one, as in `4_10`: a protein has to be
        # shared with the AD KG as well to be looked at here.
        "upstream_collection_name": "COVID_DM_CD_AF",
        "downstream_collection_name": "PD_DM_CD_AF",
        "interface_collection_names": (
            "COVID_DM_CD_AF",
            "PD_DM_CD_AF",
            "AD_KG_CD_AF",
        ),
        "max_levels": [2, 3, 4, 5, 6],
        "goat_dir_paths": {
            "upstream": INTERFACE_PD_GOAT_UPSTREAM_ANALYSIS_DIR,
            "downstream": INTERFACE_PD_GOAT_DOWNSTREAM_ANALYSIS_DIR,
            "upstream_and_downstream": (
                INTERFACE_PD_GOAT_UPSTREAM_AND_DOWNSTREAM_ANALYSIS_DIR
            ),
        },
        "intersection_dir_paths": {
            "upstream": INTERFACE_PD_INTERSECTION_UPSTREAM_ANALYSIS_DIR,
            "downstream": INTERFACE_PD_INTERSECTION_DOWNSTREAM_ANALYSIS_DIR,
            "upstream_and_downstream": (
                INTERFACE_PD_INTERSECTION_UPSTREAM_AND_DOWNSTREAM_ANALYSIS_DIR
            ),
        },
    },
    {
        # Two-way, as in `4_10`: the pairing *is* COVID and the AD KG, which
        # `2_10` stores as an ordinary CellDesigner collection.
        "name": "COVID -> AD",
        "upstream_collection_name": "COVID_DM_CD_AF",
        "downstream_collection_name": "AD_KG_CD_AF",
        "interface_collection_names": (
            "COVID_DM_CD_AF",
            "AD_KG_CD_AF",
        ),
        "max_levels": [1, 2, 3],
        "goat_dir_paths": {
            "upstream": INTERFACE_AD_GOAT_UPSTREAM_ANALYSIS_DIR,
            "downstream": INTERFACE_AD_GOAT_DOWNSTREAM_ANALYSIS_DIR,
            "upstream_and_downstream": (
                INTERFACE_AD_GOAT_UPSTREAM_AND_DOWNSTREAM_ANALYSIS_DIR
            ),
        },
        "intersection_dir_paths": {
            "upstream": INTERFACE_AD_INTERSECTION_UPSTREAM_ANALYSIS_DIR,
            "downstream": INTERFACE_AD_INTERSECTION_DOWNSTREAM_ANALYSIS_DIR,
            "upstream_and_downstream": (
                INTERFACE_AD_INTERSECTION_UPSTREAM_AND_DOWNSTREAM_ANALYSIS_DIR
            ),
        },
    },
]

## The interface and the influence structure

For each pairing we compute its interface and load the influence structure the walk needs. `load_signed_influences` is a handful of small queries and hydrates no map: these analyses walk node ids and read annotations off the database, so the `source_map` that `4_10` pays a couple of minutes for would buy them nothing.

**Two different subunit options, and they do not fight.** `WITH_SUBUNITS` above is `gea`'s: it widens a selection to its species' subunits, and is what makes a subunit contribute its gene. The interface below is taken with subunits, which decides something else entirely -- which nodes a protein **seeds** its walks from. A protein stands on every species of its collection that is it, or that contains it, so a protein held only inside a complex stands on that complex and can seed a walk after all.

In [5]:
for pairing in PAIRINGS:
    pairing["interface"] = commute_dm.core.get_interface(
        session, pairing["interface_collection_names"]
    )
    pairing["influences"] = commute_dm.submaps.load_signed_influences(
        session,
        [
            pairing["upstream_collection_name"],
            pairing["downstream_collection_name"],
        ],
    )
    # Once per pairing, not once per mode: this is a query per interface protein.
    pairing["display_names"] = commute_dm.core.get_interface_display_names(
        session, pairing["interface"]
    )

{
    pairing["name"]: {
        "n_interface": len(pairing["interface"]),
    }
    for pairing in PAIRINGS
}

{'COVID -> PD': {'n_interface': 111}, 'COVID -> AD': {'n_interface': 159}}

## GOAT enrichment

For each pairing, each mode and each level, the gene set of the selection around every interface protein is tested against every gene list. Output is one CSV per gene list per level, plus a `summary.csv` listing, per interface protein, the levels at which it came out significant — ordered by how often it did.

The three modes are the three ways to read a comorbidity sub-graph: what the interface protein is downstream of in COVID (`upstream`), what it drives in the comorbid disease (`downstream`), and both at once.

`MIN_N_NODES` applies to **both** directions, so an interface protein is skipped at a level unless each side reaches at least that many nodes — which is why the counts above are much larger than the number of proteins actually tested.

In [6]:
for pairing in PAIRINGS:
    for mode in MODES:
        output_dir_path = pairing["goat_dir_paths"][mode]
        commute_dm.utils.remake_dir(output_dir_path)
        print(f"GOAT: {pairing['name']}, {mode} -> {output_dir_path}")
        commute_dm.core.make_goat_analysis_from_interface(
            session,
            pairing["interface"],
            pairing["influences"],
            GOAT_GENE_LISTS_BUILD_DIR,
            output_dir_path,
            upstream_collection_name=pairing["upstream_collection_name"],
            downstream_collection_name=pairing["downstream_collection_name"],
            mode=mode,
            max_levels=pairing["max_levels"],
            with_subunits=WITH_SUBUNITS,
            p_value_cutoff=P_VALUE_CUTOFF,
            min_n_nodes=MIN_N_NODES,
            display_names=pairing["display_names"],
        )

GOAT: COVID -> PD, upstream -> ../../build/results/interface/analysis/pd/goat_upstream

GOAT: COVID -> PD, downstream -> ../../build/results/interface/analysis/pd/goat_downstream

GOAT: COVID -> PD, upstream_and_downstream -> ../../build/results/interface/analysis/pd/goat_upstream_and_downstream

GOAT: COVID -> AD, upstream -> ../../build/results/interface/analysis/ad/goat_upstream

GOAT: COVID -> AD, downstream -> ../../build/results/interface/analysis/ad/goat_downstream

GOAT: COVID -> AD, upstream_and_downstream -> ../../build/results/interface/analysis/ad/goat_upstream_and_downstream

## Intersection with the significant genes

The same selections, read the naive way: how much of each sub-graph's gene set is among the genes a list marks significant. Gene sets are `hgnc.symbol` here rather than `ncbigene`, because that is what the gene lists' `symbol` column holds.

This is not a test — it has no null model and no p-value, and a big sub-graph will overlap more by construction, which is exactly what GOAT above corrects for. It is here because it says *which* genes, where GOAT only says whether. The `summary.csv` orders interface proteins by the mean `|intersection| / |gene set|` over the levels.

In [7]:
for pairing in PAIRINGS:
    for mode in MODES:
        output_dir_path = pairing["intersection_dir_paths"][mode]
        commute_dm.utils.remake_dir(output_dir_path)
        print(f"intersection: {pairing['name']}, {mode} -> {output_dir_path}")
        commute_dm.core.make_intersection_analysis_from_interface(
            session,
            pairing["interface"],
            pairing["influences"],
            GOAT_GENE_LISTS_BUILD_DIR,
            output_dir_path,
            upstream_collection_name=pairing["upstream_collection_name"],
            downstream_collection_name=pairing["downstream_collection_name"],
            mode=mode,
            max_levels=pairing["max_levels"],
            with_subunits=WITH_SUBUNITS,
            min_n_nodes=MIN_N_NODES,
            display_names=pairing["display_names"],
        )

intersection: COVID -> PD, upstream -> ../../build/results/interface/analysis/pd/intersection_upstream

intersection: COVID -> PD, downstream -> ../../build/results/interface/analysis/pd/intersection_downstream

intersection: COVID -> PD, upstream_and_downstream -> ../../build/results/interface/analysis/pd/intersection_upstream_and_downstream

intersection: COVID -> AD, upstream -> ../../build/results/interface/analysis/ad/intersection_upstream

intersection: COVID -> AD, downstream -> ../../build/results/interface/analysis/ad/intersection_downstream

intersection: COVID -> AD, upstream_and_downstream -> ../../build/results/interface/analysis/ad/intersection_upstream_and_downstream

## What came out

The head of each `summary.csv`: the interface proteins whose sub-graph was most often significant (GOAT) or most heavily overlapping (intersection), per pairing and mode.

Every output table is keyed by UniProt accession (`identifier`) with the HGNC symbol beside it (`display_name`) — the same name `4_10` gives the protein's map directory. The accession stays because it is what joins the collections and what is guaranteed unique: `BBC3` is the symbol of two accessions in the current data, and `get_interface_display_names` disambiguates those as `BBC3_<accession>` rather than letting two proteins collapse into one row.

In [8]:
import os.path

import pandas

for pairing in PAIRINGS:
    for analysis, dir_paths in (
        ("goat", pairing["goat_dir_paths"]),
        ("intersection", pairing["intersection_dir_paths"]),
    ):
        for mode in MODES:
            summary_file_path = os.path.join(dir_paths[mode], "summary.csv")
            if not os.path.exists(summary_file_path):
                continue
            summary_df = pandas.read_csv(summary_file_path, index_col=0)
            print(
                f"\n=== {pairing['name']} / {analysis} / {mode} "
                f"({len(summary_df)} proteins)"
            )
            display(summary_df.head(10))

=== COVID -> PD / goat / upstream (76 proteins)

,identifier,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,deseqobj_COVID19_dopaminergic_GSE174745.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P99999,CYCS,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
1,P00403,MT-CO2,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],"[3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
2,Q96KJ9,COX4I2,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],"[3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
3,P10606,COX5B,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],"[3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
4,P13073,COX4I1,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],"[3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
5,P10176,COX8A,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],"[3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
6,P20674,COX5A,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],"[3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
7,P19404,NDUFV2,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3]",[],[],[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
8,P28331,NDUFS1,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3]",[],[],[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
9,P05231,IL6,"[3, 4, 5, 6]",[],"[4, 5, 6]",[5],"[3, 4, 5, 6]",[3],"[5, 6]",[],...,"[3, 4, 5, 6]","[4, 5, 6]","[3, 4, 5, 6]",[],[3],"[5, 6]","[3, 4, 5, 6]",[],"[3, 4, 5, 6]",[]

=== COVID -> PD / goat / downstream (76 proteins)

,identifier,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,deseqobj_COVID19_dopaminergic_GSE174745.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P00403,MT-CO2,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[2],"[3, 4, 5, 6]","[4, 5, 6]","[2, 3]",[2],...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[4, 5, 6]","[2, 3]",[],[2],"[4, 5, 6]","[2, 3, 4, 5, 6]"
1,P19404,NDUFV2,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],...,"[2, 3, 4, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
2,P28331,NDUFS1,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],...,"[2, 3, 4, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
3,Q96KJ9,COX4I2,"[4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[3, 4, 5, 6]",[],[2],...,"[4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[4, 5, 6]",[],[],[2],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
4,P10606,COX5B,"[4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[3, 4, 5, 6]",[],[2],...,"[4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[4, 5, 6]",[],[],[2],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
5,P13073,COX4I1,"[4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[3, 4, 5, 6]",[],[2],...,"[4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[4, 5, 6]",[],[],[2],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
6,P10176,COX8A,"[4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[3, 4, 5, 6]",[],[2],...,"[4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[4, 5, 6]",[],[],[2],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
7,P20674,COX5A,"[4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[3, 4, 5, 6]",[],[2],...,"[4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[4, 5, 6]",[],[],[2],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
8,P99999,CYCS,"[4, 5]","[4, 5, 6]","[4, 5, 6]",[],"[2, 3, 4, 5, 6]","[4, 5, 6]",[],[2],...,[4],"[4, 5, 6]",[],[],"[4, 5, 6]",[],[],[2],"[2, 3, 4, 5, 6]","[4, 5, 6]"
9,O60603,TLR2,"[2, 3, 4, 5, 6]",[2],[],[6],"[2, 3, 4, 5, 6]",[],[],[],...,"[2, 3, 4, 6]",[],"[4, 5, 6]",[],[],[],"[4, 5, 6]",[],"[2, 3, 4, 5, 6]",[2]

=== COVID -> PD / goat / upstream_and_downstream (76 proteins)

,identifier,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,deseqobj_COVID19_dopaminergic_GSE174745.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P00403,MT-CO2,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[6],[],"[2, 3, 4, 5, 6]",[],[6],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
1,Q96KJ9,COX4I2,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[6],[],"[2, 3, 4, 5, 6]",[],[6],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
2,P10606,COX5B,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[6],[],"[2, 3, 4, 5, 6]",[],[6],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
3,P13073,COX4I1,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[6],[],"[2, 3, 4, 5, 6]",[],[6],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
4,P10176,COX8A,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[6],[],"[2, 3, 4, 5, 6]",[],[6],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
5,P20674,COX5A,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[6],[],"[2, 3, 4, 5, 6]",[],[6],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
6,P99999,CYCS,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]",...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]",[],[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
7,P19404,NDUFV2,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[6],[],"[2, 3, 4, 5, 6]",[],[6],[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
8,P28331,NDUFS1,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],...,"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]",[6],[],"[2, 3, 4, 5, 6]",[],[6],[],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"
9,P19838,NFKB1,"[2, 3, 4, 5, 6]",[],"[2, 3, 4, 5]","[3, 4, 5, 6]","[2, 3, 4, 5, 6]",[],[],[2],...,[2],"[2, 3, 4, 5]","[2, 3, 4, 5, 6]","[5, 6]",[],[],"[2, 3, 4, 5, 6]",[2],"[2, 3, 4, 5, 6]",[]

=== COVID -> PD / intersection / upstream (76 proteins)

,identifier,score,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P01137,0.310000,TGFB1,"['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 3/5', '3: 3/5', '4: 3/5', '5: 3/5', '6: 3...","['2: 1/5', '3: 1/5', '4: 1/5', '5: 1/5', '6: 1...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 5/5', '3: 5/5', '4: 5/5', '5: 5/5', '6: 5...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...",...,"['2: 1/5', '3: 1/5', '4: 1/5', '5: 1/5', '6: 1...","['2: 1/5', '3: 1/5', '4: 1/5', '5: 1/5', '6: 1...","['2: 4/5', '3: 4/5', '4: 4/5', '5: 4/5', '6: 4...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 4/5', '3: 4/5', '4: 4/5', '5: 4/5', '6: 4...","['2: 2/5', '3: 2/5', '4: 2/5', '5: 2/5', '6: 2...","['2: 5/5', '3: 5/5', '4: 5/5', '5: 5/5', '6: 5...","['2: 3/5', '3: 3/5', '4: 3/5', '5: 3/5', '6: 3..."
1,Q00535,0.300000,CDK5,"['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 1/1', '4: 1/1', '5: 1/1', '6: 1/1']","['3: 1/1', '4: 1/1', '5: 1/1', '6: 1/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 1/1', '4: 1/1', '5: 1/1', '6: 1/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']",...,"['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 1/1', '4: 1/1', '5: 1/1', '6: 1/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 0/1', '4: 0/1', '5: 0/1', '6: 0/1']","['3: 1/1', '4: 1/1', '5: 1/1', '6: 1/1']","['3: 1/1', '4: 1/1', '5: 1/1', '6: 1/1']"
2,P61586,0.291667,RHOA,"['2: 0/6', '3: 0/6', '4: 0/6', '5: 0/6', '6: 0...","['2: 4/6', '3: 4/6', '4: 4/6', '5: 4/6', '6: 4...","['2: 1/6', '3: 1/6', '4: 1/6', '5: 1/6', '6: 1...","['2: 0/6', '3: 0/6', '4: 0/6', '5: 0/6', '6: 0...","['2: 6/6', '3: 6/6', '4: 6/6', '5: 6/6', '6: 6...","['2: 0/6', '3: 0/6', '4: 0/6', '5: 0/6', '6: 0...","['2: 0/6', '3: 0/6', '4: 0/6', '5: 0/6', '6: 0...",...,"['2: 1/6', '3: 1/6', '4: 1/6', '5: 1/6', '6: 1...","['2: 1/6', '3: 1/6', '4: 1/6', '5: 1/6', '6: 1...","['2: 4/6', '3: 4/6', '4: 4/6', '5: 4/6', '6: 4...","['2: 0/6', '3: 0/6', '4: 0/6', '5: 0/6', '6: 0...","['2: 0/6', '3: 0/6', '4: 0/6', '5: 0/6', '6: 0...","['2: 0/6', '3: 0/6', '4: 0/6', '5: 0/6', '6: 0...","['2: 4/6', '3: 4/6', '4: 4/6', '5: 4/6', '6: 4...","['2: 2/6', '3: 2/6', '4: 2/6', '5: 2/6', '6: 2...","['2: 6/6', '3: 6/6', '4: 6/6', '5: 6/6', '6: 6...","['2: 4/6', '3: 4/6', '4: 4/6', '5: 4/6', '6: 4..."
3,Q07817,0.290000,BCL2L1,"['2: 3/5', '3: 3/5', '4: 3/5', '5: 3/5', '6: 3...","['2: 2/5', '3: 2/5', '4: 2/5', '5: 2/5', '6: 2...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 4/5', '3: 4/5', '4: 4/5', '5: 4/5', '6: 4...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...",...,"['2: 1/5', '3: 1/5', '4: 1/5', '5: 1/5', '6: 1...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 4/5', '3: 4/5', '4: 4/5', '5: 4/5', '6: 4...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 4/5', '3: 4/5', '4: 4/5', '5: 4/5', '6: 4...","['2: 0/5', '3: 0/5', '4: 0/5', '5: 0/5', '6: 0...","['2: 4/5', '3: 4/5', '4: 4/5', '5: 4/5', '6: 4...","['2: 2/5', '3: 2/5', '4: 2/5', '5: 2/5', '6: 2..."
4,O75460,0.281250,ERN1,"['2: 3/8', '3: 3/8', '4: 3/8', '5: 3/8', '6: 3...","['2: 4/8', '3: 4/8', '4: 4/8', '5: 4/8', '6: 4...","['2: 2/8', '3: 2/8', '4: 2/8', '5: 2/8', '6: 2...","['2: 0/8', '3: 0/8', '4: 0/8', '5: 0/8', '6: 0...","['2: 5/8', '3: 5/8', '4: 5/8', '5: 5/8', '6: 5...","['2: 0/8', '3: 0/8', '4: 0/8', '5: 0/8', '6: 0...","['2: 0/8', '3: 0/8', '4: 0/8', '5: 0/8', '6: 0...",...,"['2: 0/8', '3: 0/8', '4: 0/8', '5: 0/8', '6: 0...","['2: 2/8', '3: 2/8', '4: 2/8', '5: 2/8', '6: 2...","['2: 6/8', '3: 6/8', '4: 6/8', '5: 6/8', '6: 6...","['2: 0/8', '3: 0/8', '4: 0/8', '5: 0/8', '6: 0...","['2: 0/8', '3: 0/8', '4: 0/8', '5: 0/8', '6: 0...","['2: 0/8', '3: 0/8', '4: 0/8', '5: 0/8', '6: 0...","['2: 6/8', '3: 6/8', '4: 6/8', '5: 6/8', '6: 6...","['2: 1/8', '3: 1/8', '4: 1/8', '5: 1/8', '6: 1...","['2: 5/8', '3: 5/8', '4: 5/8', '5: 5/8', '6: 5...","['2: 5/8', '3: 5/8', '4: 5/8', '5: 5/8', '6: 5..."
5,Q99683,0.271429,MAP3K5,"['2: 2/7', '3: 2/7', '4: 2/7', '5: 2/7', '6: 2...","['2: 4/7', '3: 4/7', '4: 4/7', '5: 4/7', '6: 4...","['2: 2/7', '3: 2/7', '4: 2/7', '5: 2/7', '6: 2...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 4/7', '3: 4/7', '4: 4/7', '5: 4/7', '6: 4...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...",...,"['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 2/7', '3: 2/7', '4: 2/7', '5: 2/7', '6: 2...","['2: 5/7', '3: 5/7', '4: 5/7', '5: 5/7', '6: 5...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 5/7', '3: 5/7', '4: 5/7', '5: 5/7', '6: 5...","['2: 1/7', '3: 1/7', '4: 1/7', '5: 1/7', '6: 1...","['2: 4/7', '3: 4/7', '4: 4/7', '5: 4/7', '6: 4...","['2: 5/7', '3: 5/7', '4: 5/7', '5: 5/7', '6: 5..."
6,P67775,0.257143,PPP2CA,"['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 3/7', '3: 3/7', '4: 3/7', '5: 3/7', '6: 3...","['2: 1/7', '3: 1/7', '4: 1/7', '5: 1/7', '6: 1...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 6/7', '3: 6/7', '4: 6/7', '5: 6/7', '6: 6...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...",...,"['2: 1/7', '3: 1/7', '4: 1/7', '5: 1/7', '6: 1...","['2: 1/7', '3: 1/7', '4: 1/7', '5: 1/7', '6: 1...","['2: 5/7', '3: 5/7', '4: 5/7', '5: 5/7', '6: 5...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 1/7', '3: 1/7', '4: 1/7', '5: 1/7', '6: 1...","['2: 0/7', '3: 0/7', '4: 0/7', '5: 0/7', '6: 0...","['2: 5/7', '3: 5/7', '4: 5/7', '5: 5/7', '6: 5...","['2: 2/7', '3: 2/7', '4: 2/7', '5: 2/7', '6: 2...","['2: 6/7', '3: 6/7', '4: 6/7', '5: 6/7', '6: 6...","['2: 3/7', '3: 3/7', '4: 3/7', '5: 3/7', '6: 3..."
7,P10415,0.256050,BCL2,"['2: 3/10', '3: 3/16', '4: 5/19', '5: 6/25', '...","['2: 2/10', '3: 6/16', '4: 8/19', '5: 11/25', ...","['2: 2/10', '3: 3/16', '4: 3/19', '5: 6/25', '...","['2: 0/10', '3: 0/16', '4: 0/19', '5: 0/25', '...","['2: 8/10', '3: 11/16', '4: 11/19', '5: 16/25'...","['2: 0/10', '3: 0/16', '4: 0/19', '5: 0/25', '...","['2: 0/10', '3: 0/16', '4: 0/19', '5: 0/25', '...",...,"['2: 1/10', '3: 1/16', '4: 2/19', '5: 2/25', '...","['2: 2/10', '3: 3/16', '4: 3/19', '5: 6/25', '...","['2: 9/10', '3: 10/16', '4: 12/19', '5: 16/25'...","['2: 0/10', '3: 0/16', '4: 0/19', '5: 0/25', '...","['2: 0/10', '3: 0/16', '4: 0/19', '5: 0/25', '...","['2: 0/10', '3: 0/16', '4: 0/19', '5: 0/25', '...","['2: 9/10', '3: 10/16', '4: 12/19', '5: 16/25'...","['2: 2/10', '3: 4/16', '4: 4/19', '5: 6/25', '...","['2: 8/10', '3: 12/16', '4: 13/19', '5: 17/25'...","['2: 2/10', '3: 6/16', '4: 8/19', '5: 12/25', ..."
8,O60603,0.250000,TLR2,"['2: 1/1', '3: 1/1', '4: 1/1', '5: 1/1', '6: 1...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...",...,"['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 1/1', '3: 1/1', '4: 1/1', '5: 1/1', '6: 1...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 1/1', '3: 1/1', '4: 1/1', '5: 1/1', '6: 1...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0...","['2: 1/1', '3: 1/1', '4: 1/1', '5: 1/1', '6: 1...","['2: 0/1', '3: 0/1', '4: 0/1', '5: 0/1', '6: 0..."
9,P17861,0.247762,XBP1,"['2: 3/6', '3: 4/10', '4: 4/12', '5: 4/12', '6...","['2: 3/6', '3: 5/10', '4: 5/12', '5: 5/12', '6...","['2: 1/6', '3: 2/10', '4: 2/12', '5: 2/12', '6...","['2: 0/6', '3: 0/10', '4: 0/12', '5: 0/12', '6...","['2: 2/6', '3: 5/10', '4: 6/12', '5: 6/12', '6...","['2: 0/6', '3: 0/10', '4: 0/12', '5: 0/12', '6...","['2: 0/6', '3: 0/10', '4: 0/12', '5: 0/12', '6...",...,"['2: 0/6', '3: 0/10', '4: 0/12', '5: 0/12', '6...","['2: 1/6', '3: 2/10', '4: 2/12', '5: 2/12', '6...","['2: 5/6', '3: 8/10', '4: 9/12', '5: 9/12', '6...","['2: 0/6', '3: 0/10', '4: 0/12', '5: 0/12', '6...","['2: 0/6', '3: 0/10', '4: 0/12', '5: 0/12', '6...","['2: 0/6', '3: 0/10', '4: 0/12', '5: 0/12', '6...","['2: 5/6', '3: 8/10', '4: 9/12', '5: 9/12', '6...","['2: 1/6', '3: 1/10', '4: 1/12', '5: 1/12', '6...","['2: 2/6', '3: 5/10', '4: 6/12', '5: 6/12', '6...","['2: 3/6', '3: 6/10', '4: 6/12', '5: 6/12', '6..."

=== COVID -> PD / intersection / downstream (76 proteins)

,identifier,score,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P25963,0.330000,NFKBIA,"['2: 1/3', '3: 1/4', '4: 1/4', '5: 1/4', '6: 1...","['2: 1/3', '3: 1/4', '4: 1/4', '5: 1/4', '6: 1...","['2: 2/3', '3: 3/4', '4: 3/4', '5: 3/4', '6: 3...","['2: 0/3', '3: 0/4', '4: 0/4', '5: 0/4', '6: 0...","['2: 3/3', '3: 3/4', '4: 3/4', '5: 3/4', '6: 3...","['2: 0/3', '3: 0/4', '4: 0/4', '5: 0/4', '6: 0...","['2: 0/3', '3: 0/4', '4: 0/4', '5: 0/4', '6: 0...",...,"['2: 1/3', '3: 1/4', '4: 1/4', '5: 1/4', '6: 1...","['2: 2/3', '3: 2/4', '4: 2/4', '5: 2/4', '6: 2...","['2: 3/3', '3: 3/4', '4: 3/4', '5: 3/4', '6: 3...","['2: 0/3', '3: 0/4', '4: 0/4', '5: 0/4', '6: 0...","['2: 1/3', '3: 1/4', '4: 1/4', '5: 1/4', '6: 1...","['2: 0/3', '3: 0/4', '4: 0/4', '5: 0/4', '6: 0...","['2: 3/3', '3: 3/4', '4: 3/4', '5: 3/4', '6: 3...","['2: 1/3', '3: 1/4', '4: 1/4', '5: 1/4', '6: 1...","['2: 3/3', '3: 3/4', '4: 3/4', '5: 3/4', '6: 3...","['2: 1/3', '3: 1/4', '4: 1/4', '5: 1/4', '6: 1..."
1,P04637,0.300000,TP53,"['2: 2/3', '3: 2/3', '4: 2/3', '5: 2/3', '6: 2...","['2: 1/3', '3: 1/3', '4: 1/3', '5: 1/3', '6: 1...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 3/3', '3: 3/3', '4: 3/3', '5: 3/3', '6: 3...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...",...,"['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 3/3', '3: 3/3', '4: 3/3', '5: 3/3', '6: 3...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 2/3', '3: 2/3', '4: 2/3', '5: 2/3', '6: 2...","['2: 0/3', '3: 0/3', '4: 0/3', '5: 0/3', '6: 0...","['2: 3/3', '3: 3/3', '4: 3/3', '5: 3/3', '6: 3...","['2: 1/3', '3: 1/3', '4: 1/3', '5: 1/3', '6: 1..."
2,P18848,0.267857,ATF4,"['3: 6/14', '4: 6/14', '5: 6/14', '6: 6/14']","['3: 6/14', '4: 6/14', '5: 6/14', '6: 6/14']","['3: 4/14', '4: 4/14', '5: 4/14', '6: 4/14']","['3: 0/14', '4: 0/14', '5: 0/14', '6: 0/14']","['3: 8/14', '4: 8/14', '5: 8/14', '6: 8/14']","['3: 0/14', '4: 0/14', '5: 0/14', '6: 0/14']","['3: 0/14', '4: 0/14', '5: 0/14', '6: 0/14']",...,"['3: 0/14', '4: 0/14', '5: 0/14', '6: 0/14']","['3: 5/14', '4: 5/14', '5: 5/14', '6: 5/14']","['3: 8/14', '4: 8/14', '5: 8/14', '6: 8/14']","['3: 0/14', '4: 0/14', '5: 0/14', '6: 0/14']","['3: 1/14', '4: 1/14', '5: 1/14', '6: 1/14']","['3: 0/14', '4: 0/14', '5: 0/14', '6: 0/14']","['3: 9/14', '4: 9/14', '5: 9/14', '6: 9/14']","['3: 4/14', '4: 4/14', '5: 4/14', '6: 4/14']","['3: 7/14', '4: 7/14', '5: 7/14', '6: 7/14']","['3: 7/14', '4: 7/14', '5: 7/14', '6: 7/14']"
3,P99999,0.252271,CYCS,"['2: 4/18', '3: 5/27', '4: 14/88', '5: 20/108'...","['2: 7/18', '3: 11/27', '4: 50/88', '5: 58/108...","['2: 3/18', '3: 6/27', '4: 22/88', '5: 25/108'...","['2: 0/18', '3: 0/27', '4: 0/88', '5: 0/108', ...","['2: 12/18', '3: 19/27', '4: 54/88', '5: 67/10...","['2: 0/18', '3: 0/27', '4: 0/88', '5: 0/108', ...","['2: 0/18', '3: 0/27', '4: 1/88', '5: 1/108', ...",...,"['2: 0/18', '3: 0/27', '4: 2/88', '5: 4/108', ...","['2: 3/18', '3: 6/27', '4: 27/88', '5: 31/108'...","['2: 14/18', '3: 18/27', '4: 40/88', '5: 54/10...","['2: 0/18', '3: 0/27', '4: 0/88', '5: 0/108', ...","['2: 1/18', '3: 1/27', '4: 7/88', '5: 8/108', ...","['2: 0/18', '3: 0/27', '4: 0/88', '5: 0/108', ...","['2: 14/18', '3: 18/27', '4: 42/88', '5: 57/10...","['2: 7/18', '3: 9/27', '4: 22/88', '5: 28/108'...","['2: 11/18', '3: 18/27', '4: 55/88', '5: 69/10...","['2: 9/18', '3: 14/27', '4: 54/88', '5: 62/108..."
4,P19404,0.249024,NDUFV2,"['2: 4/49', '3: 7/67', '4: 9/75', '5: 11/84', ...","['2: 34/49', '3: 41/67', '4: 47/75', '5: 52/84...","['2: 17/49', '3: 20/67', '4: 21/75', '5: 22/84...","['2: 0/49', '3: 0/67', '4: 0/75', '5: 0/84', '...","['2: 31/49', '3: 44/67', '4: 49/75', '5: 52/84...","['2: 0/49', '3: 0/67', '4: 0/75', '5: 0/84', '...","['2: 1/49', '3: 1/67', '4: 1/75', '5: 1/84', '...",...,"['2: 2/49', '3: 2/67', '4: 2/75', '5: 2/84', '...","['2: 22/49', '3: 25/67', '4: 26/75', '5: 28/84...","['2: 15/49', '3: 24/67', '4: 29/75', '5: 35/84...","['2: 0/49', '3: 0/67', '4: 0/75', '5: 0/84', '...","['2: 5/49', '3: 5/67', '4: 5/75', '5: 5/84', '...","['2: 0/49', '3: 0/67', '4: 0/75', '5: 0/84', '...","['2: 17/49', '3: 26/67', '4: 31/75', '5: 36/84...","['2: 13/49', '3: 17/67', '4: 18/75', '5: 22/84...","['2: 31/49', '3: 45/67', '4: 50/75', '5: 53/84...","['2: 35/49', '3: 43/67', '4: 49/75', '5: 54/84..."
5,P28331,0.249024,NDUFS1,"['2: 4/49', '3: 7/67', '4: 9/75', '5: 11/84', ...","['2: 34/49', '3: 41/67', '4: 47/75', '5: 52/84...","['2: 17/49', '3: 20/67', '4: 21/75', '5: 22/84...","['2: 0/49', '3: 0/67', '4: 0/75', '5: 0/84', '...","['2: 31/49', '3: 44/67', '4: 49/75', '5: 52/84...","['2: 0/49', '3: 0/67', '4: 0/75', '5: 0/84', '...","['2: 1/49', '3: 1/67', '4: 1/75', '5: 1/84', '...",...,"['2: 2/49', '3: 2/67', '4: 2/75', '5: 2/84', '...","['2: 22/49', '3: 25/67', '4: 26/75', '5: 28/84...","['2: 15/49', '3: 24/67', '4: 29/75', '5: 35/84...","['2: 0/49', '3: 0/67', '4: 0/75', '5: 0/84', '...","['2: 5/49', '3: 5/67', '4: 5/75', '5: 5/84', '...","['2: 0/49', '3: 0/67', '4: 0/75', '5: 0/84', '...","['2: 17/49', '3: 26/67', '4: 31/75', '5: 36/84...","['2: 13/49', '3: 17/67', '4: 18/75', '5: 22/84...","['2: 31/49', '3: 45/67', '4: 50/75', '5: 53/84...","['2: 35/49', '3: 43/67', '4: 49/75', '5: 54/84..."
6,O75460,0.248603,ERN1,"['2: 3/6', '3: 3/8', '4: 4/13', '5: 4/13', '6:...","['2: 5/6', '3: 5/8', '4: 7/13', '5: 7/13', '6:...","['2: 1/6', '3: 2/8', '4: 2/13', '5: 2/13', '6:...","['2: 0/6', '3: 0/8', '4: 0/13', '5: 0/13', '6:...","['2: 2/6', '3: 2/8', '4: 4/13', '5: 4/13', '6:...","['2: 0/6', '3: 0/8', '4: 0/13', '5: 0/13', '6:...","['2: 0/6', '3: 0/8', '4: 0/13', '5: 0/13', '6:...",...,"['2: 1/6', '3: 1/8', '4: 1/13', '5: 1/13', '6:...","['2: 1/6', '3: 2/8', '4: 2/13', '5: 2/13', '6:...","['2: 4/6', '3: 6/8', '4: 9/13', '5: 9/13', '6:...","['2: 0/6', '3: 0/8', '4: 0/13', '5: 0/13', '6:...","['2: 0/6', '3: 0/8', '4: 1/13', '5: 1/13', '6:...","['2: 0/6', '3: 0/8', '4: 0/13', '5: 0/13', '6:...","['2: 5/6', '3: 7/8', '4: 10/13', '5: 10/13', '...","['2: 1/6', '3: 2/8', '4: 2/13', '5: 2/13', '6:...","['2: 2/6', '3: 2/8', '4: 4/13', '5: 4/13', '6:...","['2: 5/6', '3: 5/8', '4: 7/13', '5: 7/13', '6:..."
7,P19525,0.244583,EIF2AK2,"['2: 0/3', '3: 0/3', '4: 1/4', '5: 6/16', '6: ...","['2: 1/3', '3: 1/3', '4: 1/4', '5: 6/16', '6: ...","['2: 2/3', '3: 2/3', '4: 2/4', '5: 5/16', '6: ...","['2: 0/3', '3: 0/3', '4: 0/4', '5: 0/16', '6: ...","['2: 1/3', '3: 1/3', '4: 2/4', '5: 8/16', '6: ...","['2: 0/3', '3: 0/3', '4: 0/4', '5: 0/16', '6: ...","['2: 0/3', '3: 0/3', '4: 0/4', '5: 0/16', '6: ...",...,"['2: 0/3', '3: 0/3', '4: 0/4', '5: 0/16', '6: ...","['2: 3/3', '3: 3/3', '4: 3/4', '5: 7/16', '6: ...","['2: 2/3', '3: 2/3', '4: 3/4', '5: 9/16', '6: ...","['2: 0/3', '3: 0/3', '4: 0/4', '5: 0/16', '6: ...","['2: 0/3', '3: 0/3', '4: 0/4', '5: 1/16', '6: ...","['2: 0/3', '3: 0/3', '4: 0/4', '5: 0/16', '6: ...","['2: 2/3', '3: 2/3', '4: 3/4', '5: 10/16', '6:...","['2: 0/3', '3: 0/3', '4: 0/4', '5: 4/16', '6: ...","['2: 1/3', '3: 1/3', '4: 2/4', '5: 7/16', '6: ...","['2: 2/3', '3: 2/3', '4: 2/4', '5: 8/16', '6: ..."
8,P35638,0.236294,DDIT3,"['2: 10/21', '3: 10/23', '4: 11/30', '5: 11/41...","['2: 9/21', '3: 11/23', '4: 14/30', '5: 18/41'...","['2: 4/21', '3: 4/23', '4: 4/30', '5: 5/41', '...","['2: 0/21', '3: 0/23', '4: 0/30', '5: 0/41', '...","['2: 10/21', '3: 11/23', '4: 13/30', '5: 15/41...","['2: 0/21', '3: 0/23', '4: 0/30', '5: 0/41', '...","['2: 0/21', '3: 0/23', '4: 0/30', '5: 0/41', '...",...,"['2: 0/21', '3: 0/23', '4: 0/30', '5: 1/41', '...","['2: 5/21', '3: 6/23', '4: 7/30', '5: 8/41', '...","['2: 15/21', '3: 15/23', '4: 17/30', '5: 20/41...","['2: 0/21', '3: 0/23', '4: 0/30', '5: 0/41', '...","['2: 0/21', '3: 0/23', '4: 0/30', '5: 1/41', '...","['2: 0/21', '3: 0/23', '4: 0/30', '5: 0/41', '...","['2: 15/21', '3: 15/23', '4: 17/30', '5: 22/41...","['2: 5/21', '3: 6/23', '4: 8/30', '5: 10/41', ...","['2: 10/21', '3: 11/23', '4: 13/30', '5: 16/41...","['2: 9/21', '3: 11/23', '4: 14/30', '5: 18/41'..."
9,Q07812,0.233590,BAX,"['2: 2/20', '3: 4/23', '4: 7/29', '5: 12/42', ...","['2: 5/20', '3: 5/23', '4: 6/29', '5: 11/42', ...","['2: 4/20', '3: 5/23', '4: 5/29', '5: 7/42', '...","['2: 0/20', '3: 0/23', '4: 0/29', '5: 0/42', '...","['2: 13/20', '3: 16/23', '4: 17/29', '5: 26/42...","['2: 0/20', '3: 0/23', '4: 0/29', '5: 0/42', '...","['2: 0/20', '3: 0/23', '4: 0/29', '5: 0/42', '...",...,"['2: 0/20', '3: 0/23', '4: 0/29', '5: 2/42', '...","['2: 5/20', '3: 6/23', '4: 6/29', '5: 8/42', '...","['2: 12/20', '3: 15/23', '4: 19/29', '5: 29/42...","['2: 0/20', '3: 0/23', '4: 0/29', '5: 0/42', '...","['2: 0/20', '3: 0/23', '4: 1/29', '5: 2/42', '...","['2: 0/20', '3: 0/23', '4: 0/29', '5: 0/42', '...","['2: 12/20', '3: 15/23', '4: 19/29', '5: 30/42...","['2: 8/20', '3: 9/23', '4: 9/29', '5: 12/42', ...","['2: 12/20', '3: 15/23', '4: 17/29', '5: 27/42...","['2: 7/20', '3: 8/23', '4: 9/29', '5: 14/42', ..."

=== COVID -> PD / intersection / upstream_and_downstream (76 proteins)

,identifier,score,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P04637,0.254520,TP53,"['2: 2/8', '3: 2/14', '4: 4/17', '5: 5/23', '6...","['2: 1/8', '3: 5/14', '4: 7/17', '5: 10/23', '...","['2: 2/8', '3: 3/14', '4: 3/17', '5: 6/23', '6...","['2: 0/8', '3: 0/14', '4: 0/17', '5: 0/23', '6...","['2: 7/8', '3: 10/14', '4: 10/17', '5: 15/23',...","['2: 0/8', '3: 0/14', '4: 0/17', '5: 0/23', '6...","['2: 0/8', '3: 0/14', '4: 0/17', '5: 0/23', '6...",...,"['2: 0/8', '3: 0/14', '4: 1/17', '5: 1/23', '6...","['2: 2/8', '3: 3/14', '4: 3/17', '5: 6/23', '6...","['2: 8/8', '3: 9/14', '4: 11/17', '5: 15/23', ...","['2: 0/8', '3: 0/14', '4: 0/17', '5: 0/23', '6...","['2: 0/8', '3: 0/14', '4: 0/17', '5: 0/23', '6...","['2: 0/8', '3: 0/14', '4: 0/17', '5: 0/23', '6...","['2: 7/8', '3: 8/14', '4: 10/17', '5: 14/23', ...","['2: 2/8', '3: 4/14', '4: 4/17', '5: 6/23', '6...","['2: 7/8', '3: 11/14', '4: 12/17', '5: 16/23',...","['2: 1/8', '3: 5/14', '4: 7/17', '5: 11/23', '..."
1,O75460,0.244417,ERN1,"['2: 5/12', '3: 5/14', '4: 6/19', '5: 6/19', '...","['2: 7/12', '3: 7/14', '4: 9/19', '5: 9/19', '...","['2: 2/12', '3: 3/14', '4: 3/19', '5: 3/19', '...","['2: 0/12', '3: 0/14', '4: 0/19', '5: 0/19', '...","['2: 6/12', '3: 6/14', '4: 8/19', '5: 8/19', '...","['2: 0/12', '3: 0/14', '4: 0/19', '5: 0/19', '...","['2: 0/12', '3: 0/14', '4: 0/19', '5: 0/19', '...",...,"['2: 1/12', '3: 1/14', '4: 1/19', '5: 1/19', '...","['2: 2/12', '3: 3/14', '4: 3/19', '5: 3/19', '...","['2: 8/12', '3: 10/14', '4: 13/19', '5: 13/19'...","['2: 0/12', '3: 0/14', '4: 0/19', '5: 0/19', '...","['2: 0/12', '3: 0/14', '4: 1/19', '5: 1/19', '...","['2: 0/12', '3: 0/14', '4: 0/19', '5: 0/19', '...","['2: 9/12', '3: 11/14', '4: 14/19', '5: 14/19'...","['2: 1/12', '3: 2/14', '4: 2/19', '5: 2/19', '...","['2: 6/12', '3: 6/14', '4: 8/19', '5: 8/19', '...","['2: 8/12', '3: 8/14', '4: 10/19', '5: 10/19',..."
2,Q07817,0.235846,BCL2L1,"['2: 7/27', '3: 7/29', '4: 11/38', '5: 17/53',...","['2: 12/27', '3: 12/29', '4: 13/38', '5: 18/53...","['2: 2/27', '3: 3/29', '4: 3/38', '5: 6/53', '...","['2: 0/27', '3: 0/29', '4: 0/38', '5: 0/53', '...","['2: 19/27', '3: 20/29', '4: 22/38', '5: 32/53...","['2: 0/27', '3: 0/29', '4: 0/38', '5: 0/53', '...","['2: 0/27', '3: 0/29', '4: 0/38', '5: 0/53', '...",...,"['2: 1/27', '3: 1/29', '4: 1/38', '5: 3/53', '...","['2: 2/27', '3: 3/29', '4: 3/38', '5: 6/53', '...","['2: 18/27', '3: 20/29', '4: 25/38', '5: 36/53...","['2: 0/27', '3: 0/29', '4: 0/38', '5: 0/53', '...","['2: 1/27', '3: 1/29', '4: 2/38', '5: 3/53', '...","['2: 0/27', '3: 0/29', '4: 0/38', '5: 0/53', '...","['2: 18/27', '3: 20/29', '4: 25/38', '5: 37/53...","['2: 5/27', '3: 6/29', '4: 6/38', '5: 10/53', ...","['2: 18/27', '3: 19/29', '4: 22/38', '5: 33/53...","['2: 15/27', '3: 15/29', '4: 16/38', '5: 22/53..."
3,Q99683,0.234931,MAP3K5,"['2: 4/20', '3: 7/28', '4: 8/36', '5: 12/49', ...","['2: 8/20', '3: 10/28', '4: 12/36', '5: 13/49'...","['2: 5/20', '3: 6/28', '4: 8/36', '5: 9/49', '...","['2: 0/20', '3: 0/28', '4: 0/36', '5: 0/49', '...","['2: 11/20', '3: 14/28', '4: 20/36', '5: 25/49...","['2: 0/20', '3: 0/28', '4: 0/36', '5: 0/49', '...","['2: 0/20', '3: 0/28', '4: 0/36', '5: 0/49', '...",...,"['2: 0/20', '3: 0/28', '4: 0/36', '5: 0/49', '...","['2: 6/20', '3: 7/28', '4: 9/36', '5: 11/49', ...","['2: 11/20', '3: 15/28', '4: 21/36', '5: 29/49...","['2: 0/20', '3: 0/28', '4: 0/36', '5: 0/49', '...","['2: 1/20', '3: 1/28', '4: 1/36', '5: 3/49', '...","['2: 0/20', '3: 0/28', '4: 0/36', '5: 0/49', '...","['2: 11/20', '3: 15/28', '4: 21/36', '5: 29/49...","['2: 6/20', '3: 9/28', '4: 12/36', '5: 13/49',...","['2: 11/20', '3: 14/28', '4: 20/36', '5: 26/49...","['2: 9/20', '3: 11/28', '4: 13/36', '5: 15/49'..."
4,P19525,0.232179,EIF2AK2,"['2: 2/12', '3: 3/15', '4: 4/16', '5: 9/28', '...","['2: 4/12', '3: 4/15', '4: 4/16', '5: 9/28', '...","['2: 6/12', '3: 9/15', '4: 9/16', '5: 12/28', ...","['2: 0/12', '3: 0/15', '4: 0/16', '5: 0/28', '...","['2: 5/12', '3: 6/15', '4: 7/16', '5: 13/28', ...","['2: 0/12', '3: 0/15', '4: 0/16', '5: 0/28', '...","['2: 2/12', '3: 3/15', '4: 3/16', '5: 3/28', '...",...,"['2: 0/12', '3: 0/15', '4: 0/16', '5: 0/28', '...","['2: 7/12', '3: 10/15', '4: 10/16', '5: 14/28'...","['2: 5/12', '3: 7/15', '4: 8/16', '5: 14/28', ...","['2: 0/12', '3: 0/15', '4: 0/16', '5: 0/28', '...","['2: 0/12', '3: 0/15', '4: 0/16', '5: 1/28', '...","['2: 0/12', '3: 0/15', '4: 0/16', '5: 0/28', '...","['2: 7/12', '3: 9/15', '4: 10/16', '5: 17/28',...","['2: 0/12', '3: 0/15', '4: 0/16', '5: 4/28', '...","['2: 5/12', '3: 6/15', '4: 7/16', '5: 12/28', ...","['2: 8/12', '3: 8/15', '4: 8/16', '5: 14/28', ..."
5,O43521,0.231862,BCL2L11,"['2: 4/15', '3: 5/18', '4: 8/26', '5: 13/38', ...","['2: 7/15', '3: 9/18', '4: 12/26', '5: 17/38',...","['2: 4/15', '3: 6/18', '4: 7/26', '5: 8/38', '...","['2: 0/15', '3: 0/18', '4: 0/26', '5: 0/38', '...","['2: 5/15', '3: 8/18', '4: 11/26', '5: 20/38',...","['2: 0/15', '3: 0/18', '4: 0/26', '5: 0/38', '...","['2: 0/15', '3: 0/18', '4: 0/26', '5: 0/38', '...",...,"['2: 0/15', '3: 0/18', '4: 0/26', '5: 2/38', '...","['2: 4/15', '3: 6/18', '4: 7/26', '5: 8/38', '...","['2: 7/15', '3: 9/18', '4: 15/26', '5: 24/38',...","['2: 0/15', '3: 0/18', '4: 0/26', '5: 0/38', '...","['2: 0/15', '3: 0/18', '4: 1/26', '5: 2/38', '...","['2: 0/15', '3: 0/18', '4: 0/26', '5: 0/38', '...","['2: 7/15', '3: 9/18', '4: 15/26', '5: 25/38',...","['2: 2/15', '3: 4/18', '4: 4/26', '5: 6/38', '...","['2: 6/15', '3: 9/18', '4: 13/26', '5: 23/38',...","['2: 8/15', '3: 10/18', '4: 13/26', '5: 18/38'..."
6,P10415,0.231585,BCL2,"['2: 5/27', '3: 5/33', '4: 8/40', '5: 10/48', ...","['2: 9/27', '3: 13/33', '4: 15/40', '5: 18/48'...","['2: 3/27', '3: 4/33', '4: 4/40', '5: 8/48', '...","['2: 0/27', '3: 0/33', '4: 0/40', '5: 0/48', '...","['2: 19/27', '3: 22/33', '4: 24/40', '5: 31/48...","['2: 0/27', '3: 0/33', '4: 0/40', '5: 0/48', '...","['2: 0/27', '3: 0/33', '4: 0/40', '5: 0/48', '...",...,"['2: 1/27', '3: 1/33', '4: 2/40', '5: 2/48', '...","['2: 3/27', '3: 4/33', '4: 4/40', '5: 9/48', '...","['2: 20/27', '3: 21/33', '4: 24/40', '5: 29/48...","['2: 0/27', '3: 0/33', '4: 0/40', '5: 0/48', '...","['2: 0/27', '3: 0/33', '4: 0/40', '5: 0/48', '...","['2: 0/27', '3: 0/33', '4: 0/40', '5: 0/48', '...","['2: 20/27', '3: 21/33', '4: 24/40', '5: 29/48...","['2: 5/27', '3: 7/33', '4: 7/40', '5: 9/48', '...","['2: 19/27', '3: 23/33', '4: 26/40', '5: 32/48...","['2: 12/27', '3: 16/33', '4: 18/40', '5: 23/48..."
7,P35638,0.227465,DDIT3,"['2: 12/27', '3: 13/33', '4: 16/48', '5: 16/67...","['2: 11/27', '3: 16/33', '4: 23/48', '5: 30/67...","['2: 5/27', '3: 7/33', '4: 8/48', '5: 12/67', ...","['2: 0/27', '3: 0/33', '4: 0/48', '5: 0/67', '...","['2: 11/27', '3: 13/33', '4: 18/48', '5: 25/67...","['2: 0/27', '3: 0/33', '4: 0/48', '5: 0/67', '...","['2: 0/27', '3: 0/33', '4: 0/48', '5: 0/67', '...",...,"['2: 0/27', '3: 0/33', '4: 1/48', '5: 2/67', '...","['2: 6/27', '3: 9/33', '4: 11/48', '5: 15/67',...","['2: 18/27', '3: 20/33', '4: 27/48', '5: 34/67...","['2: 0/27', '3: 0/33', '4: 0/48', '5: 0/67', '...","['2: 0/27', '3: 0/33', '4: 0/48', '5: 1/67', '...","['2: 0/27', '3: 0/33', '4: 0/48', '5: 0/67', '...","['2: 18/27', '3: 20/33', '4: 27/48', '5: 36/67...","['2: 6/27', '3: 9/33', '4: 11/48', '5: 14/67',...","['2: 11/27', '3: 13/33', '4: 19/48', '5: 26/67...","['2: 12/27', '3: 18/33', '4: 26/48', '5: 34/67..."
8,P25963,0.226588,NFKBIA,"['2: 5/17', '3: 7/26', '4: 11/38', '5: 13/44',...","['2: 7/17', '3: 10/26', '4: 15/38', '5: 15/44'...","['2: 3/17', '3: 6/26', '4: 9/38', '5: 9/44', '...","['2: 0/17', '3: 0/26', '4: 0/38', '5: 0/44', '...","['2: 10/17', '3: 12/26', '4: 18/38', '5: 21/44...","['2: 0/17', '3: 0/26', '4: 0/38', '5: 0/44', '...","['2: 0/17', '3: 0/26', '4: 0/38', '5: 0/44', '...",...,"['2: 1/17', '3: 2/26', '4: 2/38', '5: 2/44', '...","['2: 3/17', '3: 5/26', '4: 8/38', '5: 8/44', '...","['2: 10/17', '3: 15/26', '4: 21/38', '5: 22/44...","['2: 0/17', '3: 0/26', '4: 0/38', '5: 0/44', '...","['2: 1/17', '3: 1/26', '4: 1/38', '5: 1/44', '...","['2: 0/17', '3: 0/26', '4: 0/38', '5: 0/44', '...","['2: 10/17', '3: 17/26', '4: 23/38', '5: 24/44...","['2: 6/17', '3: 6/26', '4: 8/38', '5: 9/44', '...","['2: 11/17', '3: 14/26', '4: 19/38', '5: 22/44...","['2: 7/17', '3: 10/26', '4: 16/38', '5: 16/44'..."
9,P18848,0.226574,ATF4,"['3: 6/17', '4: 6/21', '5: 7/22', '6: 7/23']","['3: 7/17', '4: 8/21', '5: 9/22', '6: 9/23']","['3: 4/17', '4: 5/21', '5: 5/22', '6: 5/23']","['3: 0/17', '4: 0/21', '5: 0/22', '6: 0/23']","['3: 9/17', '4: 10/21', '5: 11/22', '6: 11/23']","['3: 0/17', '4: 0/21', '5: 0/22', '6: 0/23']","['3: 0/17', '4: 0/21', '5: 0/22', '6: 0/23']",...,"['3: 0/17', '4: 0/21', '5: 0/22', '6: 0/23']","['3: 5/17', '4: 6/21', '5: 6/22', '6: 6/23']","['3: 9/17', '4: 11/21', '5: 12/22', '6: 13/23']","['3: 0/17', '4: 0/21', '5: 0/22', '6: 0/23']","['3: 1/17', '4: 1/21', '5: 1/22', '6: 1/23']","['3: 0/17', '4: 0/21', '5: 0/22', '6: 0/23']","['3: 10/17', '4: 12/21', '5: 13/22', '6: 14/23']","['3: 4/17', '4: 4/21', '5: 4/22', '6: 4/23']","['3: 8/17', '4: 9/21', '5: 10/22', '6: 10/23']","['3: 8/17', '4: 10/21', '5: 11/22', '6: 11/23']"

=== COVID -> AD / goat / upstream (77 proteins)

,identifier,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,deseqobj_COVID19_dopaminergic_GSE174745.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P99999,CYCS,"[2, 3]","[1, 2, 3]","[1, 2, 3]",[],"[2, 3]","[2, 3]",[],"[2, 3]",...,"[2, 3]","[1, 2, 3]",[],[],"[2, 3]",[],[],"[2, 3]","[2, 3]","[2, 3]"
1,P00403,MT-CO2,"[2, 3]","[2, 3]","[2, 3]",[],"[2, 3]","[2, 3]",[],[3],...,"[2, 3]","[2, 3]",[],[],"[2, 3]",[],[],[3],"[2, 3]","[2, 3]"
2,P19838,NFKB1,"[2, 3]",[],"[2, 3]",[],"[2, 3]",[],[],[1],...,"[1, 2]","[2, 3]","[1, 3]",[],[],[],"[1, 3]",[1],"[2, 3]",[]
3,P19404,NDUFV2,"[2, 3]","[2, 3]","[2, 3]",[],"[2, 3]","[2, 3]",[],[],...,"[2, 3]","[2, 3]",[],[],[],[],[],[],"[2, 3]","[2, 3]"
4,P28331,NDUFS1,"[2, 3]","[2, 3]","[2, 3]",[],"[2, 3]","[2, 3]",[],[],...,"[2, 3]","[2, 3]",[],[],[],[],[],[],"[2, 3]","[2, 3]"
5,Q04206,RELA,"[2, 3]",[],"[2, 3]",[],"[2, 3]",[],[],[],...,"[1, 2]","[2, 3]",[3],[],[],[],[3],[],"[2, 3]",[]
6,Q96P20,NLRP3,"[2, 3]",[],[],[],"[2, 3]","[2, 3]",[],[],...,[3],[],[3],[],"[2, 3]",[],[3],[],"[2, 3]",[]
7,Q16539,MAPK14,"[2, 3]",[],"[2, 3]",[],[3],[],[],[],...,[],"[2, 3]",[3],[],[],[],[3],[],[3],[]
8,Q9Y4K3,TRAF6,"[2, 3]",[],"[2, 3]",[],"[2, 3]",[],[],[],...,[],"[2, 3]",[],[],[],[],[],[],"[2, 3]",[]
9,P01584,IL1B,[3],[],[],[],[3],[3],[],[],...,[3],[],[3],[],[3],[],[3],[],[3],[2]

=== COVID -> AD / goat / downstream (77 proteins)

,identifier,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,deseqobj_COVID19_dopaminergic_GSE174745.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P01584,IL1B,"[1, 2, 3]",[3],"[1, 2, 3]","[2, 3]","[1, 2, 3]",[3],"[1, 2, 3]",[],...,"[1, 2, 3]","[1, 2, 3]","[1, 2, 3]",[3],[],"[1, 2, 3]","[1, 2, 3]",[],"[1, 2, 3]","[2, 3]"
1,P19838,NFKB1,"[2, 3]",[3],"[2, 3]","[2, 3]","[2, 3]",[3],"[2, 3]",[],...,"[1, 2, 3]","[2, 3]",[3],[3],[],"[2, 3]","[2, 3]",[],"[2, 3]",[3]
2,P01375,TNF,"[2, 3]",[],"[1, 3]",[3],"[1, 3]",[3],"[1, 2, 3]",[],...,"[2, 3]","[1, 3]","[1, 2, 3]",[3],[],[3],"[1, 2, 3]",[],"[1, 3]",[3]
3,P02792,FTL,"[2, 3]",[3],"[2, 3]","[2, 3]","[2, 3]",[],"[2, 3]",[],...,"[2, 3]","[2, 3]","[2, 3]",[3],[],[3],"[2, 3]",[],"[2, 3]",[3]
4,P36222,CHI3L1,"[2, 3]",[],"[2, 3]","[2, 3]","[2, 3]",[3],"[2, 3]",[],...,"[2, 3]","[2, 3]","[2, 3]",[3],[],[3],"[2, 3]",[],"[2, 3]",[]
5,P01137,TGFB1,"[2, 3]",[3],"[2, 3]","[2, 3]","[2, 3]",[],[3],[],...,"[2, 3]","[2, 3]","[2, 3]",[3],[],[3],"[2, 3]",[],"[2, 3]",[3]
6,Q14790,CASP8,"[2, 3]",[3],"[2, 3]","[2, 3]","[2, 3]",[],[3],[],...,"[2, 3]","[2, 3]","[2, 3]",[3],[],[3],"[2, 3]",[],"[2, 3]",[3]
7,P01031,C5,"[2, 3]",[3],"[2, 3]",[3],"[2, 3]",[],"[2, 3]",[],...,[3],"[2, 3]","[2, 3]",[3],[],"[2, 3]","[2, 3]",[],"[2, 3]",[3]
8,Q8WTV0,SCARB1,"[2, 3]",[3],"[2, 3]",[3],"[2, 3]",[],"[2, 3]",[],...,"[2, 3]","[2, 3]",[2],[],[],"[2, 3]",[2],[],"[2, 3]",[3]
9,P06702,S100A9,"[2, 3]","[2, 3]",[3],"[2, 3]",[3],[3],"[2, 3]",[],...,"[2, 3]",[3],[],[3],[3],[3],[],[],[3],"[2, 3]"

=== COVID -> AD / goat / upstream_and_downstream (77 proteins)

,identifier,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,deseqobj_COVID19_dopaminergic_GSE174745.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,P01584,IL1B,"[1, 2, 3]",[3],"[1, 2, 3]","[2, 3]","[1, 2, 3]",[3],"[1, 2, 3]",[],...,"[1, 2, 3]","[1, 2, 3]","[1, 2, 3]",[3],[],[3],"[1, 2, 3]",[],"[1, 2, 3]","[2, 3]"
1,P19838,NFKB1,"[2, 3]",[3],"[2, 3]","[2, 3]","[2, 3]",[],"[2, 3]",[1],...,"[1, 2, 3]","[2, 3]","[2, 3]",[3],[],"[2, 3]","[2, 3]",[1],"[2, 3]",[3]
2,P01137,TGFB1,"[2, 3]",[3],"[2, 3]","[2, 3]","[1, 2, 3]",[],[3],[],...,"[2, 3]","[2, 3]","[1, 2, 3]",[3],[],[3],"[1, 2, 3]",[],"[1, 2, 3]",[3]
3,P01375,TNF,"[2, 3]",[],"[1, 3]",[3],"[1, 3]",[],"[1, 2, 3]",[],...,"[2, 3]","[1, 3]","[1, 2, 3]",[3],[],[3],"[1, 2, 3]",[],"[1, 3]",[3]
4,P99999,CYCS,"[2, 3]","[2, 3]","[1, 2, 3]",[],"[2, 3]","[2, 3]",[3],[],...,"[2, 3]","[1, 2, 3]",[],[],"[2, 3]",[3],[],[2],"[2, 3]","[2, 3]"
5,P02792,FTL,"[2, 3]",[3],"[2, 3]","[2, 3]","[2, 3]",[],"[2, 3]",[],...,"[2, 3]","[2, 3]","[2, 3]",[3],[],[3],"[2, 3]",[],"[2, 3]",[3]
6,P01031,C5,"[2, 3]",[3],"[2, 3]","[2, 3]","[2, 3]",[],"[2, 3]",[],...,"[2, 3]","[2, 3]","[2, 3]",[3],[],"[2, 3]","[2, 3]",[],"[2, 3]",[3]
7,P00403,MT-CO2,[2],"[2, 3]","[2, 3]",[],"[2, 3]","[2, 3]",[3],[3],...,"[2, 3]","[2, 3]",[],[],"[2, 3]",[3],[],[3],"[2, 3]","[2, 3]"
8,P36222,CHI3L1,"[2, 3]",[],"[2, 3]","[2, 3]","[2, 3]",[3],[3],[],...,"[2, 3]","[2, 3]","[2, 3]",[3],[],[3],"[2, 3]",[],"[2, 3]",[]
9,P19525,EIF2AK2,[3],[2],"[1, 2, 3]","[1, 2, 3]",[3],[],"[2, 3]",[],...,[3],"[1, 2, 3]",[3],[3],[],[3],[3],[],[3],"[1, 2, 3]"

=== COVID -> AD / intersection / upstream (77 proteins)

,identifier,score,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,Q14116,0.336667,IL18,"['2: 4/5', '3: 4/6']","['2: 2/5', '3: 2/6']","['2: 1/5', '3: 2/6']","['2: 0/5', '3: 0/6']","['2: 4/5', '3: 5/6']","['2: 0/5', '3: 0/6']","['2: 0/5', '3: 0/6']",...,"['2: 1/5', '3: 1/6']","['2: 1/5', '3: 2/6']","['2: 5/5', '3: 6/6']","['2: 0/5', '3: 0/6']","['2: 1/5', '3: 1/6']","['2: 0/5', '3: 0/6']","['2: 4/5', '3: 5/6']","['2: 1/5', '3: 1/6']","['2: 3/5', '3: 4/6']","['2: 2/5', '3: 2/6']"
1,P01137,0.310000,TGFB1,"['1: 0/5', '2: 0/5', '3: 0/5']","['1: 3/5', '2: 3/5', '3: 3/5']","['1: 1/5', '2: 1/5', '3: 1/5']","['1: 0/5', '2: 0/5', '3: 0/5']","['1: 5/5', '2: 5/5', '3: 5/5']","['1: 0/5', '2: 0/5', '3: 0/5']","['1: 0/5', '2: 0/5', '3: 0/5']",...,"['1: 1/5', '2: 1/5', '3: 1/5']","['1: 1/5', '2: 1/5', '3: 1/5']","['1: 4/5', '2: 4/5', '3: 4/5']","['1: 0/5', '2: 0/5', '3: 0/5']","['1: 0/5', '2: 0/5', '3: 0/5']","['1: 0/5', '2: 0/5', '3: 0/5']","['1: 4/5', '2: 4/5', '3: 4/5']","['1: 2/5', '2: 2/5', '3: 2/5']","['1: 5/5', '2: 5/5', '3: 5/5']","['1: 3/5', '2: 3/5', '3: 3/5']"
2,Q00535,0.300000,CDK5,['3: 0/1'],['3: 1/1'],['3: 1/1'],['3: 0/1'],['3: 1/1'],['3: 0/1'],['3: 0/1'],...,['3: 0/1'],['3: 1/1'],['3: 0/1'],['3: 0/1'],['3: 0/1'],['3: 0/1'],['3: 0/1'],['3: 0/1'],['3: 1/1'],['3: 1/1']
3,Q07817,0.285000,BCL2L1,"['1: 2/4', '2: 3/5', '3: 3/5']","['1: 2/4', '2: 2/5', '3: 2/5']","['1: 0/4', '2: 0/5', '3: 0/5']","['1: 0/4', '2: 0/5', '3: 0/5']","['1: 3/4', '2: 4/5', '3: 4/5']","['1: 0/4', '2: 0/5', '3: 0/5']","['1: 0/4', '2: 0/5', '3: 0/5']",...,"['1: 1/4', '2: 1/5', '3: 1/5']","['1: 0/4', '2: 0/5', '3: 0/5']","['1: 3/4', '2: 4/5', '3: 4/5']","['1: 0/4', '2: 0/5', '3: 0/5']","['1: 0/4', '2: 0/5', '3: 0/5']","['1: 0/4', '2: 0/5', '3: 0/5']","['1: 3/4', '2: 4/5', '3: 4/5']","['1: 0/4', '2: 0/5', '3: 0/5']","['1: 3/4', '2: 4/5', '3: 4/5']","['1: 2/4', '2: 2/5', '3: 2/5']"
4,P35228,0.273125,NOS2,"['2: 3/5', '3: 4/8']","['2: 2/5', '3: 2/8']","['2: 1/5', '3: 1/8']","['2: 0/5', '3: 0/8']","['2: 3/5', '3: 4/8']","['2: 0/5', '3: 0/8']","['2: 0/5', '3: 0/8']",...,"['2: 1/5', '3: 1/8']","['2: 1/5', '3: 1/8']","['2: 3/5', '3: 5/8']","['2: 0/5', '3: 0/8']","['2: 1/5', '3: 1/8']","['2: 0/5', '3: 0/8']","['2: 3/5', '3: 5/8']","['2: 1/5', '3: 2/8']","['2: 3/5', '3: 5/8']","['2: 3/5', '3: 4/8']"
5,P10599,0.272500,TXN,"['2: 0/2', '3: 1/5']","['2: 1/2', '3: 2/5']","['2: 0/2', '3: 2/5']","['2: 0/2', '3: 0/5']","['2: 2/2', '3: 3/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']",...,"['2: 0/2', '3: 0/5']","['2: 1/2', '3: 3/5']","['2: 0/2', '3: 2/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 2/5']","['2: 2/2', '3: 2/5']","['2: 2/2', '3: 3/5']","['2: 1/2', '3: 3/5']"
6,Q99683,0.271429,MAP3K5,"['2: 2/7', '3: 2/7']","['2: 4/7', '3: 4/7']","['2: 2/7', '3: 2/7']","['2: 0/7', '3: 0/7']","['2: 4/7', '3: 4/7']","['2: 0/7', '3: 0/7']","['2: 0/7', '3: 0/7']",...,"['2: 0/7', '3: 0/7']","['2: 2/7', '3: 2/7']","['2: 5/7', '3: 5/7']","['2: 0/7', '3: 0/7']","['2: 0/7', '3: 0/7']","['2: 0/7', '3: 0/7']","['2: 5/7', '3: 5/7']","['2: 1/7', '3: 1/7']","['2: 4/7', '3: 4/7']","['2: 5/7', '3: 5/7']"
7,P10415,0.269062,BCL2,"['2: 3/10', '3: 3/16']","['2: 2/10', '3: 6/16']","['2: 2/10', '3: 3/16']","['2: 0/10', '3: 0/16']","['2: 8/10', '3: 11/16']","['2: 0/10', '3: 0/16']","['2: 0/10', '3: 0/16']",...,"['2: 1/10', '3: 1/16']","['2: 2/10', '3: 3/16']","['2: 9/10', '3: 10/16']","['2: 0/10', '3: 0/16']","['2: 0/10', '3: 0/16']","['2: 0/10', '3: 0/16']","['2: 9/10', '3: 10/16']","['2: 2/10', '3: 4/16']","['2: 8/10', '3: 12/16']","['2: 2/10', '3: 6/16']"
8,P49662,0.265000,CASP4,"['2: 1/2', '3: 1/5']","['2: 1/2', '3: 2/5']","['2: 1/2', '3: 2/5']","['2: 0/2', '3: 0/5']","['2: 1/2', '3: 2/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']",...,"['2: 0/2', '3: 0/5']","['2: 1/2', '3: 2/5']","['2: 1/2', '3: 4/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']","['2: 1/2', '3: 3/5']","['2: 1/2', '3: 1/5']","['2: 1/2', '3: 2/5']","['2: 1/2', '3: 2/5']"
9,P17861,0.261667,XBP1,"['2: 3/6', '3: 4/10']","['2: 3/6', '3: 5/10']","['2: 1/6', '3: 2/10']","['2: 0/6', '3: 0/10']","['2: 2/6', '3: 5/10']","['2: 0/6', '3: 0/10']","['2: 0/6', '3: 0/10']",...,"['2: 0/6', '3: 0/10']","['2: 1/6', '3: 2/10']","['2: 5/6', '3: 8/10']","['2: 0/6', '3: 0/10']","['2: 0/6', '3: 0/10']","['2: 0/6', '3: 0/10']","['2: 5/6', '3: 8/10']","['2: 1/6', '3: 1/10']","['2: 2/6', '3: 5/10']","['2: 3/6', '3: 6/10']"

=== COVID -> AD / intersection / downstream (77 proteins)

,identifier,score,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,Q07812,0.316667,BAX,"['2: 1/3', '3: 1/3']","['2: 2/3', '3: 2/3']","['2: 2/3', '3: 2/3']","['2: 0/3', '3: 0/3']","['2: 1/3', '3: 1/3']","['2: 0/3', '3: 0/3']","['2: 0/3', '3: 0/3']",...,"['2: 1/3', '3: 1/3']","['2: 2/3', '3: 2/3']","['2: 2/3', '3: 2/3']","['2: 0/3', '3: 0/3']","['2: 0/3', '3: 0/3']","['2: 0/3', '3: 0/3']","['2: 2/3', '3: 2/3']","['2: 1/3', '3: 1/3']","['2: 1/3', '3: 1/3']","['2: 2/3', '3: 2/3']"
1,P01100,0.267500,FOS,"['2: 2/2', '3: 2/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']","['2: 2/2', '3: 4/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 0/5']",...,"['2: 0/2', '3: 0/5']","['2: 1/2', '3: 1/5']","['2: 2/2', '3: 3/5']","['2: 0/2', '3: 0/5']","['2: 0/2', '3: 1/5']","['2: 0/2', '3: 0/5']","['2: 2/2', '3: 4/5']","['2: 0/2', '3: 0/5']","['2: 2/2', '3: 4/5']","['2: 0/2', '3: 0/5']"
2,P05362,0.258333,ICAM1,"['2: 1/1', '3: 5/6']","['2: 0/1', '3: 1/6']","['2: 1/1', '3: 1/6']","['2: 0/1', '3: 0/6']","['2: 0/1', '3: 1/6']","['2: 0/1', '3: 0/6']","['2: 0/1', '3: 0/6']",...,"['2: 0/1', '3: 0/6']","['2: 1/1', '3: 1/6']","['2: 1/1', '3: 3/6']","['2: 0/1', '3: 0/6']","['2: 0/1', '3: 1/6']","['2: 0/1', '3: 0/6']","['2: 1/1', '3: 3/6']","['2: 0/1', '3: 1/6']","['2: 0/1', '3: 1/6']","['2: 0/1', '3: 2/6']"
3,Q14116,0.250000,IL18,"['2: 1/1', '3: 1/2']","['2: 0/1', '3: 1/2']","['2: 0/1', '3: 0/2']","['2: 0/1', '3: 0/2']","['2: 1/1', '3: 1/2']","['2: 0/1', '3: 0/2']","['2: 0/1', '3: 0/2']",...,"['2: 0/1', '3: 0/2']","['2: 0/1', '3: 0/2']","['2: 1/1', '3: 1/2']","['2: 0/1', '3: 0/2']","['2: 0/1', '3: 0/2']","['2: 0/1', '3: 0/2']","['2: 1/1', '3: 1/2']","['2: 0/1', '3: 0/2']","['2: 1/1', '3: 1/2']","['2: 0/1', '3: 1/2']"
4,P04637,0.231667,TP53,"['2: 2/3', '3: 2/5']","['2: 1/3', '3: 2/5']","['2: 1/3', '3: 1/5']","['2: 0/3', '3: 0/5']","['2: 1/3', '3: 3/5']","['2: 0/3', '3: 0/5']","['2: 0/3', '3: 0/5']",...,"['2: 0/3', '3: 0/5']","['2: 1/3', '3: 1/5']","['2: 2/3', '3: 2/5']","['2: 0/3', '3: 0/5']","['2: 0/3', '3: 0/5']","['2: 0/3', '3: 0/5']","['2: 1/3', '3: 1/5']","['2: 1/3', '3: 2/5']","['2: 1/3', '3: 3/5']","['2: 1/3', '3: 3/5']"
5,P05412,0.218254,JUN,"['1: 1/3', '2: 1/3', '3: 22/105']","['1: 1/3', '2: 1/3', '3: 25/105']","['1: 2/3', '2: 2/3', '3: 15/105']","['1: 0/3', '2: 0/3', '3: 0/105']","['1: 2/3', '2: 2/3', '3: 35/105']","['1: 0/3', '2: 0/3', '3: 0/105']","['1: 0/3', '2: 0/3', '3: 0/105']",...,"['1: 0/3', '2: 0/3', '3: 1/105']","['1: 2/3', '2: 2/3', '3: 14/105']","['1: 0/3', '2: 0/3', '3: 37/105']","['1: 0/3', '2: 0/3', '3: 0/105']","['1: 0/3', '2: 0/3', '3: 5/105']","['1: 0/3', '2: 0/3', '3: 0/105']","['1: 1/3', '2: 1/3', '3: 41/105']","['1: 0/3', '2: 0/3', '3: 13/105']","['1: 2/3', '2: 2/3', '3: 37/105']","['1: 1/3', '2: 1/3', '3: 33/105']"
6,P40763,0.214316,STAT3,"['2: 4/9', '3: 8/26']","['2: 3/9', '3: 9/26']","['2: 3/9', '3: 6/26']","['2: 0/9', '3: 0/26']","['2: 5/9', '3: 8/26']","['2: 0/9', '3: 0/26']","['2: 0/9', '3: 0/26']",...,"['2: 2/9', '3: 4/26']","['2: 3/9', '3: 6/26']","['2: 6/9', '3: 8/26']","['2: 0/9', '3: 0/26']","['2: 0/9', '3: 0/26']","['2: 0/9', '3: 0/26']","['2: 6/9', '3: 8/26']","['2: 1/9', '3: 1/26']","['2: 5/9', '3: 8/26']","['2: 3/9', '3: 11/26']"
7,Q12933,0.208333,TRAF2,"['2: 1/2', '3: 1/3']","['2: 1/2', '3: 1/3']","['2: 0/2', '3: 0/3']","['2: 0/2', '3: 0/3']","['2: 1/2', '3: 1/3']","['2: 0/2', '3: 0/3']","['2: 0/2', '3: 0/3']",...,"['2: 0/2', '3: 0/3']","['2: 0/2', '3: 0/3']","['2: 1/2', '3: 1/3']","['2: 0/2', '3: 0/3']","['2: 0/2', '3: 0/3']","['2: 0/2', '3: 0/3']","['2: 1/2', '3: 1/3']","['2: 1/2', '3: 1/3']","['2: 1/2', '3: 1/3']","['2: 1/2', '3: 1/3']"
8,P67775,0.197889,PPP2CA,"['1: 1/10', '2: 11/50', '3: 35/150']","['1: 3/10', '2: 15/50', '3: 43/150']","['1: 2/10', '2: 13/50', '3: 27/150']","['1: 0/10', '2: 0/50', '3: 0/150']","['1: 7/10', '2: 20/50', '3: 49/150']","['1: 0/10', '2: 0/50', '3: 0/150']","['1: 0/10', '2: 0/50', '3: 0/150']",...,"['1: 0/10', '2: 0/50', '3: 2/150']","['1: 2/10', '2: 13/50', '3: 27/150']","['1: 7/10', '2: 21/50', '3: 59/150']","['1: 0/10', '2: 0/50', '3: 0/150']","['1: 1/10', '2: 1/50', '3: 6/150']","['1: 0/10', '2: 0/50', '3: 0/150']","['1: 7/10', '2: 22/50', '3: 62/150']","['1: 3/10', '2: 11/50', '3: 24/150']","['1: 7/10', '2: 20/50', '3: 51/150']","['1: 3/10', '2: 15/50', '3: 49/150']"
9,P01137,0.192834,TGFB1,"['1: 2/6', '2: 18/64', '3: 49/216']","['1: 2/6', '2: 10/64', '3: 51/216']","['1: 1/6', '2: 12/64', '3: 37/216']","['1: 0/6', '2: 0/64', '3: 1/216']","['1: 3/6', '2: 22/64', '3: 70/216']","['1: 0/6', '2: 0/64', '3: 0/216']","['1: 0/6', '2: 0/64', '3: 0/216']",...,"['1: 1/6', '2: 2/64', '3: 5/216']","['1: 2/6', '2: 14/64', '3: 37/216']","['1: 4/6', '2: 28/64', '3: 76/216']","['1: 0/6', '2: 0/64', '3: 0/216']","['1: 1/6', '2: 4/64', '3: 8/216']","['1: 0/6', '2: 0/64', '3: 0/216']","['1: 5/6', '2: 29/64', '3: 83/216']","['1: 1/6', '2: 11/64', '3: 28/216']","['1: 3/6', '2: 23/64', '3: 72/216']","['1: 2/6', '2: 14/64', '3: 66/216']"

=== COVID -> AD / intersection / upstream_and_downstream (77 proteins)

,identifier,score,display_name,dgeobj_MS_brain_GSE123496.csv,dgeobj_COVID19_pbmc_GSE152418.csv,dgeobj_COVID19_cl_GSE147507.csv,deseqobj_PD_brain_GSE216281.csv,deseqobj_AD_brain_GSE95587.csv,dgeobj_PD_brain_GSE136666.csv,deseqobj_COVID19_hipsc_GSE179923.csv,...,deseqobj_COVID19_pbmc_GSE251849.csv,deseqobj_COVID19_cl_GSE147507.csv,dgeobj_PD_brain_GSE68719.csv,dgeobj_PD_brain_GSE216281.csv,deseqobj_PD_brain_GSE136666.csv,dgeobj_COVID19_hipsc_GSE179923.csv,deseqobj_PD_brain_GSE68719.csv,dgeobj_COVID19_dopaminergic_GSE174745.csv,dgeobj_AD_brain_GSE95587.csv,deseqobj_COVID19_pbmc_GSE152418.csv
0,Q14116,0.320000,IL18,"['2: 4/5', '3: 4/7']","['2: 2/5', '3: 3/7']","['2: 1/5', '3: 2/7']","['2: 0/5', '3: 0/7']","['2: 4/5', '3: 5/7']","['2: 0/5', '3: 0/7']","['2: 0/5', '3: 0/7']",...,"['2: 1/5', '3: 1/7']","['2: 1/5', '3: 2/7']","['2: 5/5', '3: 6/7']","['2: 0/5', '3: 0/7']","['2: 1/5', '3: 1/7']","['2: 0/5', '3: 0/7']","['2: 4/5', '3: 5/7']","['2: 1/5', '3: 1/7']","['2: 3/5', '3: 4/7']","['2: 2/5', '3: 3/7']"
1,P04637,0.248438,TP53,"['2: 2/8', '3: 2/16']","['2: 1/8', '3: 6/16']","['2: 3/8', '3: 4/16']","['2: 0/8', '3: 0/16']","['2: 5/8', '3: 10/16']","['2: 0/8', '3: 0/16']","['2: 0/8', '3: 0/16']",...,"['2: 0/8', '3: 0/16']","['2: 3/8', '3: 4/16']","['2: 7/8', '3: 8/16']","['2: 0/8', '3: 0/16']","['2: 0/8', '3: 0/16']","['2: 0/8', '3: 0/16']","['2: 6/8', '3: 7/16']","['2: 3/8', '3: 6/16']","['2: 5/8', '3: 11/16']","['2: 1/8', '3: 7/16']"
2,P01100,0.233611,FOS,"['2: 5/15', '3: 10/36']","['2: 3/15', '3: 13/36']","['2: 4/15', '3: 11/36']","['2: 0/15', '3: 0/36']","['2: 7/15', '3: 16/36']","['2: 0/15', '3: 0/36']","['2: 0/15', '3: 0/36']",...,"['2: 0/15', '3: 1/36']","['2: 5/15', '3: 12/36']","['2: 9/15', '3: 19/36']","['2: 0/15', '3: 0/36']","['2: 0/15', '3: 1/36']","['2: 0/15', '3: 0/36']","['2: 10/15', '3: 21/36']","['2: 4/15', '3: 7/36']","['2: 8/15', '3: 18/36']","['2: 4/15', '3: 15/36']"
3,Q12933,0.231944,TRAF2,"['2: 3/12', '3: 3/18']","['2: 5/12', '3: 7/18']","['2: 6/12', '3: 8/18']","['2: 0/12', '3: 0/18']","['2: 6/12', '3: 8/18']","['2: 0/12', '3: 0/18']","['2: 0/12', '3: 0/18']",...,"['2: 0/12', '3: 0/18']","['2: 6/12', '3: 8/18']","['2: 6/12', '3: 8/18']","['2: 0/12', '3: 0/18']","['2: 0/12', '3: 0/18']","['2: 0/12', '3: 0/18']","['2: 7/12', '3: 9/18']","['2: 1/12', '3: 3/18']","['2: 7/12', '3: 8/18']","['2: 6/12', '3: 9/18']"
4,P25963,0.227691,NFKBIA,"['2: 5/18', '3: 10/32']","['2: 7/18', '3: 12/32']","['2: 4/18', '3: 6/32']","['2: 0/18', '3: 0/32']","['2: 10/18', '3: 12/32']","['2: 0/18', '3: 0/32']","['2: 0/18', '3: 0/32']",...,"['2: 1/18', '3: 2/32']","['2: 3/18', '3: 5/32']","['2: 10/18', '3: 17/32']","['2: 0/18', '3: 0/32']","['2: 1/18', '3: 1/32']","['2: 0/18', '3: 0/32']","['2: 10/18', '3: 19/32']","['2: 6/18', '3: 6/32']","['2: 11/18', '3: 14/32']","['2: 7/18', '3: 13/32']"
5,Q07812,0.224123,BAX,"['2: 4/15', '3: 6/19']","['2: 6/15', '3: 8/19']","['2: 4/15', '3: 5/19']","['2: 0/15', '3: 0/19']","['2: 5/15', '3: 8/19']","['2: 0/15', '3: 0/19']","['2: 0/15', '3: 0/19']",...,"['2: 2/15', '3: 2/19']","['2: 4/15', '3: 5/19']","['2: 9/15', '3: 11/19']","['2: 0/15', '3: 0/19']","['2: 0/15', '3: 0/19']","['2: 0/15', '3: 0/19']","['2: 9/15', '3: 11/19']","['2: 2/15', '3: 3/19']","['2: 6/15', '3: 9/19']","['2: 6/15', '3: 8/19']"
6,P10415,0.222147,BCL2,"['2: 3/16', '3: 3/23']","['2: 2/16', '3: 6/23']","['2: 2/16', '3: 3/23']","['2: 0/16', '3: 0/23']","['2: 11/16', '3: 14/23']","['2: 0/16', '3: 0/23']","['2: 0/16', '3: 0/23']",...,"['2: 1/16', '3: 1/23']","['2: 2/16', '3: 3/23']","['2: 13/16', '3: 14/23']","['2: 0/16', '3: 0/23']","['2: 0/16', '3: 0/23']","['2: 0/16', '3: 0/23']","['2: 13/16', '3: 14/23']","['2: 4/16', '3: 6/23']","['2: 10/16', '3: 14/23']","['2: 2/16', '3: 6/23']"
7,P99999,0.209001,CYCS,"['1: 1/18', '2: 14/140', '3: 30/219']","['1: 8/18', '2: 83/140', '3: 102/219']","['1: 4/18', '2: 32/140', '3: 39/219']","['1: 0/18', '2: 0/140', '3: 0/219']","['1: 10/18', '2: 73/140', '3: 94/219']","['1: 0/18', '2: 0/140', '3: 0/219']","['1: 1/18', '2: 3/140', '3: 3/219']",...,"['1: 0/18', '2: 4/140', '3: 5/219']","['1: 5/18', '2: 41/140', '3: 47/219']","['1: 6/18', '2: 54/140', '3: 85/219']","['1: 0/18', '2: 0/140', '3: 0/219']","['1: 0/18', '2: 13/140', '3: 14/219']","['1: 0/18', '2: 0/140', '3: 0/219']","['1: 7/18', '2: 57/140', '3: 90/219']","['1: 6/18', '2: 40/140', '3: 51/219']","['1: 8/18', '2: 71/140', '3: 93/219']","['1: 8/18', '2: 85/140', '3: 110/219']"
8,P01137,0.208855,TGFB1,"['1: 2/10', '2: 18/68', '3: 49/220']","['1: 5/10', '2: 13/68', '3: 54/220']","['1: 2/10', '2: 13/68', '3: 38/220']","['1: 0/10', '2: 0/68', '3: 1/220']","['1: 7/10', '2: 26/68', '3: 74/220']","['1: 0/10', '2: 0/68', '3: 0/220']","['1: 0/10', '2: 0/68', '3: 0/220']",...,"['1: 2/10', '2: 3/68', '3: 6/220']","['1: 3/10', '2: 15/68', '3: 38/220']","['1: 7/10', '2: 31/68', '3: 79/220']","['1: 0/10', '2: 0/68', '3: 0/220']","['1: 1/10', '2: 4/68', '3: 8/220']","['1: 0/10', '2: 0/68', '3: 0/220']","['1: 8/10', '2: 32/68', '3: 86/220']","['1: 3/10', '2: 13/68', '3: 30/220']","['1: 7/10', '2: 27/68', '3: 76/220']","['1: 5/10', '2: 17/68', '3: 69/220']"
9,P45984,0.207844,MAPK9,"['1: 1/8', '2: 1/20', '3: 32/143']","['1: 1/8', '2: 7/20', '3: 42/143']","['1: 3/8', '2: 5/20', '3: 27/143']","['1: 0/8', '2: 0/20', '3: 0/143']","['1: 4/8', '2: 8/20', '3: 44/143']","['1: 0/8', '2: 0/20', '3: 0/143']","['1: 0/8', '2: 0/20', '3: 0/143']",...,"['1: 0/8', '2: 0/20', '3: 3/143']","['1: 3/8', '2: 5/20', '3: 26/143']","['1: 6/8', '2: 10/20', '3: 55/143']","['1: 0/8', '2: 0/20', '3: 0/143']","['1: 0/8', '2: 0/20', '3: 4/143']","['1: 0/8', '2: 0/20', '3: 0/143']","['1: 7/8', '2: 11/20', '3: 59/143']","['1: 3/8', '2: 7/20', '3: 23/143']","['1: 4/8', '2: 9/20', '3: 48/143']","['1: 1/8', '2: 7/20', '3: 48/143']"